apiVersion: apps/v1
kind: Deployment
metadata:
  name: sudoku-api-deployment
  labels:
    app: sudoku-ai
spec:
  replicas: 2  # Chạy song song 2 Pods để chia tải
  selector:
    matchLabels:
      app: sudoku-ai
  template:
    metadata:
      labels:
        app: sudoku-ai
    spec:
      containers:
      - name: sudoku-api
        # Đổi 'username_cua_ban' thành username Docker Hub của bạn (ví dụ: luonganh1/sudoku-solver:latest)
        # Hoặc nếu chưa push lên Docker Hub, dùng image local bạn vừa build bằng Docker
        image: luonganh1/sudoku-solver:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000 # Cổng FastAPI trong Dockerfile của bạn
        resources:
          requests:
            memory: "512Mi"   # Tăng mức tối thiểu RAM lên 512MB
            cpu: "500m"       # Mức CPU tối thiểu (0.5 nhân)
          limits:
            memory: "1Gi"     # Tăng trần RAM lên 1GB (cho OpenCV load ảnh thoải mái)
            cpu: "1000m"    # Tăng trần CPU lên 1 NGUYÊN NHÂN (1000m = 1 vCPU) giúp AI nhận diện siêu nhanh!